name: gdi_app
description: GDI Index — Plataforma de Estudos Educa/Meggy
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1
  webview_flutter_android: ^3.12.1
  shared_preferences: ^2.2.2
  flutter_inappwebview: ^6.0.0
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
